import styles from './styles.module.css';
import {Icon} from '../../Icon';
import {useEffect, useRef, useState} from 'react';

type Experience = 'Table' | 'Afternoon Tea' | 'Bottomless Brunch';
type Props = {experience: Experience; prices: Record<Experience, number>; price: number; total: number; guestCount: number; date: string; formatDate: (date: string) => string; showDatePicker: boolean; onToggleDatePicker: () => void; visibleMonth: Date; onPreviousMonth: () => void; onNextMonth: () => void; calendarDays: Date[]; today: string; onSelectDate: (value: string) => void; guests: string; onGuestsChange: (value: string) => void; times: string[]; selectedTime: string; onTimeChange: (value: string) => void; showAllTimes: boolean; onToggleTimes: () => void; onExperienceChange: (value: Experience) => void; afternoonTeaUpgrade: boolean; onAfternoonTeaUpgradeChange: (value: boolean) => void; bottomlessBrunchUpgrade: boolean; onBottomlessBrunchUpgradeChange: (value: boolean) => void; bottomlessBrunchMeal: string; bottomlessBrunchMeals: {name: string; description: string}[]; onBottomlessBrunchMealChange: (value: string) => void; onContinue: () => void};
const quickGuestOptions = ['2 Guests', '3 Guests', '4 Guests', '5 Guests', '6+ Guests'];
const largePartyOptions = Array.from({length: 15}, (_, index) => index + 6);

export function BookingScreen({experience, prices, price, total, guestCount, date, formatDate, showDatePicker, onToggleDatePicker, visibleMonth, onPreviousMonth, onNextMonth, calendarDays, today, onSelectDate, guests, onGuestsChange, times, selectedTime, onTimeChange, showAllTimes, onToggleTimes, onExperienceChange, afternoonTeaUpgrade, onAfternoonTeaUpgradeChange, bottomlessBrunchUpgrade, onBottomlessBrunchUpgradeChange, bottomlessBrunchMeal, bottomlessBrunchMeals, onBottomlessBrunchMealChange, onContinue}: Props) {
  const inputDate = (value: Date) => value.toISOString().slice(0, 10);
  const isLargeParty = guestCount >= 6;
  const [showBrunchMeals, setShowBrunchMeals] = useState(false);
  const rootRef = useRef<HTMLDivElement>(null);
  useEffect(() => {
    if (!showBrunchMeals) return;
    const scrollSurface = rootRef.current?.closest('.content') as HTMLElement | null;
    if (!scrollSurface) return;
    const previousValue = scrollSurface.style.getPropertyValue('overflow-y');
    const previousPriority = scrollSurface.style.getPropertyPriority('overflow-y');
    scrollSurface.style.setProperty('overflow-y', 'hidden', 'important');
    return () => scrollSurface.style.setProperty('overflow-y', previousValue, previousPriority);
  }, [showBrunchMeals]);
  return <div ref={rootRef} className={styles.root}>
    <p className="eyebrow">Reserve your visit</p><h1>Good food starts<br/>right here.</h1>
    <div className="bookingTypes" aria-label="Choose your experience">{(['Table', 'Afternoon Tea', 'Bottomless Brunch'] as const).map(option => <button type="button" className={experience === option ? 'selected' : ''} onClick={() => onExperienceChange(option)} key={option}><span>{option}</span>{prices[option] > 0 && <small>£{prices[option].toFixed(2)} pp</small>}</button>)}</div>
    {experience === 'Afternoon Tea' && <fieldset className={styles.afternoonTeaUpgrade}><legend>Afternoon Tea upgrade</legend><label><input type="radio" name="afternoon-tea-upgrade" checked={!afternoonTeaUpgrade} onChange={() => onAfternoonTeaUpgradeChange(false)}/><span><b>No drink upgrade</b><small>Summer Afternoon Tea · £{prices['Afternoon Tea'].toFixed(2)} per person</small></span></label><label><input type="radio" name="afternoon-tea-upgrade" checked={afternoonTeaUpgrade} onChange={() => onAfternoonTeaUpgradeChange(true)}/><span><b>Add Pimms or Prosecco</b><small>£5.00 per person · Juice and non-alcoholic Prosecco available</small></span></label></fieldset>}
    {experience === 'Bottomless Brunch' && <><fieldset className={styles.afternoonTeaUpgrade}><legend>Bottomless Brunch drinks</legend><label><input type="radio" name="bottomless-brunch-upgrade" checked={!bottomlessBrunchUpgrade} onChange={() => onBottomlessBrunchUpgradeChange(false)}/><span><b>Classic drinks included</b><small>Prosecco, Pimms, house gin or vodka, and draught soft drinks</small></span></label><label><input type="radio" name="bottomless-brunch-upgrade" checked={bottomlessBrunchUpgrade} onChange={() => onBottomlessBrunchUpgradeChange(true)}/><span><b>Upgrade drinks selection</b><small>£5.00 per person · Cocktails, mocktails or non-alcoholic choices</small></span></label></fieldset><button type="button" className={styles.mealPicker} onClick={() => setShowBrunchMeals(true)}><span><small>Brunch dish</small><b>{bottomlessBrunchMeal || 'Choose your included dish'}</b></span><Icon name="fa-chevron-right"/></button>{showBrunchMeals && <div className={styles.mealOverlay} role="dialog" aria-modal="true" aria-label="Choose your brunch dish" onTouchMove={event => {if (!(event.target as HTMLElement).closest(`.${styles.mealList}`)) event.preventDefault();}} onWheel={event => {if (!(event.target as HTMLElement).closest(`.${styles.mealList}`)) event.preventDefault();}}><section className={styles.mealSheet}><button type="button" className={styles.closeMeals} onClick={() => setShowBrunchMeals(false)} aria-label="Close meal choices"><Icon name="fa-xmark"/></button><p className="eyebrow">Bottomless Brunch</p><h2>Choose your<br/>included dish.</h2><p>One dish is included with every guest’s booking.</p><div className={styles.mealList}>{bottomlessBrunchMeals.map(meal => <button type="button" className={bottomlessBrunchMeal === meal.name ? styles.selectedMeal : ''} key={meal.name} onClick={() => {onBottomlessBrunchMealChange(meal.name); setShowBrunchMeals(false);}}><span><b>{meal.name}</b><small>{meal.description}</small></span><Icon name={bottomlessBrunchMeal === meal.name ? 'fa-circle-check' : 'fa-chevron-right'}/></button>)}</div></section></div>}</>}
    {price > 0 && <section className="experiencePrice"><Icon name="fa-sparkles"/><span><small>{experience}</small><b>£{price.toFixed(2)} <em>per guest</em></b></span><strong>£{total.toFixed(2)}<small>for {guestCount} guests</small></strong></section>}
    <button type="button" className="dateField" aria-expanded={showDatePicker} onClick={onToggleDatePicker}><span>{formatDate(date)}</span><Icon name="fa-chevron-down"/></button>
    {showDatePicker && <section className="datePicker" aria-label="Choose a booking date"><header><button type="button" aria-label="Previous month" disabled={visibleMonth.getFullYear() === new Date().getFullYear() && visibleMonth.getMonth() === new Date().getMonth()} onClick={onPreviousMonth}><Icon name="fa-chevron-left"/></button><b>{visibleMonth.toLocaleDateString('en-GB', {month: 'long', year: 'numeric'})}</b><button type="button" aria-label="Next month" onClick={onNextMonth}><Icon name="fa-chevron-right"/></button></header><div className="weekdays">{['M','T','W','T','F','S','S'].map((day,index) => <span key={`${day}-${index}`}>{day}</span>)}</div><div className="calendarDays">{calendarDays.map(value => {const key = inputDate(value); const outside = value.getMonth() !== visibleMonth.getMonth(); return <button type="button" key={key} disabled={outside || key < today} className={date === key ? 'selected' : ''} onClick={() => onSelectDate(key)}>{value.getDate()}</button>;})}</div></section>}
    <div className="chips" aria-label="Choose number of guests">{quickGuestOptions.map(option => {const isLargeOption = option === '6+ Guests'; return <button type="button" className={(isLargeOption ? isLargeParty : guests === option) ? 'selected' : ''} onClick={() => onGuestsChange(isLargeOption ? `${Math.max(6, guestCount)} Guests` : option)} key={option}>{option}</button>;})}</div>
    {isLargeParty && <label className={styles.largeParty}><span>Party size</span><select value={guestCount} onChange={event => onGuestsChange(`${event.target.value} Guests`)} aria-label="Party size">{largePartyOptions.map(option => <option value={option} key={option}>{option} guests</option>)}</select></label>}
    <div className="sectionTitle">Choose a time <button type="button" onClick={onToggleTimes}>{showAllTimes ? 'Show fewer' : 'View all times'}</button></div>{times.length ? <div className="times">{(showAllTimes ? times : times.slice(0,6)).map(option => <button type="button" className={selectedTime === option ? 'selected' : ''} onClick={() => onTimeChange(option)} key={option}>{option}</button>)}</div> : <p className="noTimes">There are no more {experience.toLowerCase()} times today. Choose another date to see availability.</p>}
    <p className="notice"><b>{experience === 'Table' ? 'Member moment' : `${experience} booking`}</b><br/>{experience === 'Bottomless Brunch' ? 'Available Monday to Saturday from noon until 7:30 PM. Choose your included dish to continue.' : experience === 'Afternoon Tea' ? 'Booking is essential at least 24 hours in advance.' : `Reserve at ${selectedTime || 'an available time'} and earn double points on your seasonal menu.`}</p><button className="cta" disabled={!selectedTime || experience === 'Bottomless Brunch' && !bottomlessBrunchMeal} onClick={onContinue}>Continue to details</button>
  </div>;
}
