import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteFooter, SiteHeader } from '../SiteChrome';
import { ArrowIcon } from '../WhatsAppLink';
import { metadata } from '../../lib/seo';
import PricingCards from './PricingCards';

export const generateMetadata = (): Metadata => metadata('Pricing | Pace', 'Simple, venue-focused pricing for Pace restaurant management software.', '/pricing');

export default function PricingPage() {
  return <><SiteHeader/><main tabIndex={-1} id="main" className="subpage pricing-page wrap"><p className="eyebrow">PRICING THAT FITS THE VENUE</p><h1>Start with what you need. <em>Grow from there.</em></h1><p className="subpage-intro">Choose the back-office tools your venue needs, with starting prices shown below. Guest app scope, setup costs and contract terms are confirmed separately in your quote.</p><PricingCards/><section className="pricing-clarity" aria-labelledby="quote-details"><h2 id="quote-details">Know what your quote covers.</h2><dl><div><dt>Companion guest app</dt><dd>App inclusion and rollout scope are confirmed in your quote. The starting prices above do not specify an included guest app package.</dd></div><div><dt>Setup and onboarding</dt><dd>These may be quoted separately. A fixed setup fee is not published; ask for an itemised total for your venue.</dd></div><div><dt>Contract and cancellation</dt><dd>Confirm whether your chosen plan is monthly or annual, the renewal price and any minimum term before committing.</dd></div></dl></section><section className="pricing-details"><div><p className="eyebrow">NO SURPRISES</p><h2>What we’ll consider.</h2></div><div className="pricing-detail-list"><p><strong>Venue setup</strong> — the number of venues, tables and menus you need to manage.</p><p><strong>Team workflow</strong> — the people who need access and the way your service is organised.</p><p><strong>Support and rollout</strong> — whether you need help getting started or are planning a wider deployment.</p><p><strong>Pilot shape</strong> — the workflow you want to prove first, the success questions to review and the path to expansion.</p><p><strong>Future connections</strong> — the systems you may want to connect later, without presenting planned API access as live today.</p></div></section><div className="subpage-callout"><h2>Not sure which plan fits?</h2><p>Tell us how your venue works and we’ll help you find a sensible starting point.</p><Link className="button" href="/contact">Talk to the Pace team <span><ArrowIcon/></span></Link></div></main><SiteFooter/></>;
}
