import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteFooter, SiteHeader } from '../SiteChrome';
import { metadata } from '../../lib/seo';

export const generateMetadata = (): Metadata => metadata('Pricing | Pace', 'Simple, venue-focused pricing for Pace restaurant management software.', '/pricing');

const plans: {name: string; price: string; cadence: string; summary: string; features: string[]; cta: string}[] = [
  {name: 'Pace essentials', price: '£59', cadence: 'per venue / month', summary: 'For venues getting their daily operations into one place.', features: ['Booking diary and table assignments', 'Venue and kitchen hours', 'Menu sections, dishes and availability'], cta: 'Start a conversation'},
  {name: 'Pace growth', price: '£99', cadence: 'per venue / month', summary: 'For teams ready to connect service planning with customer loyalty.', features: ['Everything in Pace essentials', 'Customer points and reward codes', 'Reward expiry and activity history'], cta: 'Talk through your needs'},
  {name: 'Pace group', price: 'Custom', cadence: 'multi-venue pricing', summary: 'For growing hospitality businesses with more than one venue.', features: ['A rollout shaped around your venues', 'Shared operating standards', 'A plan for permissions, support and future integrations'], cta: 'Plan a rollout'},
];

export default function PricingPage() {
  return <><SiteHeader/><main className="subpage pricing-page wrap"><p className="eyebrow">PRICING THAT FITS THE VENUE</p><h1>Start with what you need. <em>Grow from there.</em></h1><p className="subpage-intro">Clear, transparent starting prices for the connected operation and companion guest app. Pace is designed to give independent venues a more accessible route into modern hospitality software, without hiding the starting point behind a sales conversation.</p><div className="pricing-grid">{plans.map(plan=><article key={plan.name}><span className="pricing-label">{plan.name}</span><p className="pricing-price">{plan.price}</p><p className="pricing-cadence">{plan.cadence}</p><h2>{plan.summary}</h2><ul>{plan.features.map(feature=><li key={feature}><span>✓</span>{feature}</li>)}</ul><Link className="button" href="/contact">{plan.cta} <span>↗</span></Link></article>)}</div><p className="pricing-footnote">Prices shown are before VAT. Setup, onboarding, payment processing, SMS and third-party services may be quoted separately. Group pricing depends on venue count, rollout scope and support needs. Competitor pricing varies by quote, usage and add-ons, so we recommend comparing the complete cost rather than a headline subscription alone.</p><section className="pricing-details"><div><p className="eyebrow">NO SURPRISES</p><h2>What we’ll consider.</h2></div><div className="pricing-detail-list"><p><strong>Venue setup</strong> — the number of venues, tables and menus you need to manage.</p><p><strong>Team workflow</strong> — the people who need access and the way your service is organised.</p><p><strong>Support and rollout</strong> — whether you need help getting started or are planning a wider deployment.</p><p><strong>Pilot shape</strong> — the workflow you want to prove first, the success questions to review and the path to expansion.</p><p><strong>Future connections</strong> — the systems you may want to connect later, without presenting planned API access as live today.</p></div></section><div className="subpage-callout"><h2>Not sure which plan fits?</h2><p>Tell us how your venue works and we’ll help you find a sensible starting point.</p><Link className="button" href="/contact">Talk to the Pace team <span>↗</span></Link></div></main><SiteFooter/></>;
}
