'use client';
import { useState } from 'react';
import Link from 'next/link';
import { features as seoFeatures } from '../lib/features';
import { SiteFooter } from './SiteChrome';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronDown } from '@fortawesome/free-solid-svg-icons';
import { ArrowIcon, WhatsAppArrow, whatsappUrl } from './WhatsAppLink';
const features = [
  { name: 'Bookings', eyebrow: 'A clearer view of service', title: 'Every table. Every booking. One place.', description: 'See what’s coming, assign the right tables and keep your team a step ahead. Set service hours that work for your kitchen.', points: ['A visual booking diary', 'Table capacities and assignments', 'Configurable kitchen closing times'] },
  { name: 'Menus', eyebrow: 'Keep everyone on the same page', title: 'Your menu, ready for service.', description: 'Keep dishes, prices and availability organised from one back office, with dietary information where your team needs it.', points: ['Organised menus and sections', 'Dish prices and availability', 'Dietary information'] },
  { name: 'Rewards', eyebrow: 'Give them a reason to return', title: 'A little thank you goes a long way.', description: 'Create points rewards with individual QR codes, choose their expiry and add customer points with a clear record of every credit.', points: ['Single-use reward codes', 'Flexible points and expiry dates', 'Customer balances and history'] },
];
function Logo({dark=false}:{dark?:boolean}) { return <span className="logo"><img src={`/branding/pace-${dark?'dark':'light'}.png`} width="1448" height="1086" alt="Pace — Service in Sync" /></span>; }
function Diary({compact=false}:{compact?:boolean}) { return <div className={`diary ${compact?'compact':''}`} aria-label="Illustrative booking diary">
  <div className="diary-top"><div><span className="mini-label">YOUR SERVICE, AT A GLANCE</span><h3>Friday’s looking good.</h3></div><span className="live"><i/> Service ready</span></div>
  <div className="diary-stats"><div><b>24</b><span>reservations</span></div><div><b>86</b><span>guests expected</span></div><div><b>12</b><span>tables in sync</span></div><span className="date-chip">FRI, 18 SEPT</span></div>
  <div className="timeline"><div className="time-row"><span>TABLE</span>{['17:00','18:00','19:00','20:00','21:00'].map(t=><span key={t}>{t}</span>)}</div>
    {[['01','2 seats','Olivia · 2 guests','early'],['02','4 seats','James · 4 guests','late'],['03','6 seats','Sophie · 6 guests','middle'],['04','2 seats','Amir · 2 guests','early'],['05','4 seats','Ella · 3 guests','late']].map(([id,seats,name,position],i)=><div className="table-row" key={id}><div className="table-label"><b>{id}</b><small>{seats}</small></div><div className="track"><div className={`reservation ${position} shade-${i%3}`}><b>{name}</b><small>Confirmed</small></div></div></div>)}
  </div><div className="diary-bottom"><span><i/> Everything in its place.</span><small>Illustrative product view</small></div>
</div>; }
export default function Home(){ const [active,setActive]=useState(0);const [menu,setMenu]=useState(false); const feature=features[active];return <>
  <a className="skip" href="#main">Skip to content</a>
  <header className="header"><Link href="/" aria-label="Pace home"><Logo/></Link><button className={`menu-toggle${menu?' is-open':''}`} aria-expanded={menu} aria-controls="navigation" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}><span/><span/><span/></button><nav id="navigation" className={menu?'open':''} aria-label="Main navigation"><Link href="/capabilities" onClick={()=>setMenu(false)}>Capabilities</Link><Link href="/platform" onClick={()=>setMenu(false)}>The platform</Link><Link href="/app" onClick={()=>setMenu(false)}>Guest app</Link><Link href="/pricing" onClick={()=>setMenu(false)}>Pricing</Link><Link href="/developers" onClick={()=>setMenu(false)}>Developers</Link><Link href="/how-it-works" onClick={()=>setMenu(false)}>How it works</Link><Link href="/faqs" onClick={()=>setMenu(false)}>FAQs</Link><div className="nav-dropdown"><button className="nav-dropdown-trigger" type="button">Explore <FontAwesomeIcon icon={faChevronDown} aria-hidden="true"/></button><div className="nav-dropdown-panel"><Link href="/about" onClick={()=>setMenu(false)}>About Pace</Link><Link href="/integrations" onClick={()=>setMenu(false)}>Integrations</Link><Link href="/use-cases" onClick={()=>setMenu(false)}>Use cases</Link><Link href="/resources" onClick={()=>setMenu(false)}>Resources</Link><Link href="/restaurants" onClick={()=>setMenu(false)}>For restaurants</Link><Link href="/cafes" onClick={()=>setMenu(false)}>For cafés</Link><Link href="/pubs-bars" onClick={()=>setMenu(false)}>For pubs & bars</Link><Link href="/customer-journey" onClick={()=>setMenu(false)}>Customer journey</Link><Link href="/for-venue-owners" onClick={()=>setMenu(false)}>For venue owners</Link><Link href="/implementation" onClick={()=>setMenu(false)}>Implementation</Link><Link href="/product-tour" onClick={()=>setMenu(false)}>Product tour</Link></div></div></nav><a className="button button-small header-cta" href={whatsappUrl} target="_blank" rel="noreferrer">Talk to Pace <WhatsAppArrow/></a></header>
  <main id="main"><section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span/> RESTAURANT & HOSPITALITY MANAGEMENT SOFTWARE</p><h1>Great service.<br/>Less friction.<br/><em>That’s Pace.</em></h1><p className="intro">Restaurant management software that brings your bookings, menus and customer rewards together. More time for your guests. A better rhythm for your team.</p><div className="hero-actions"><Link className="button" href="/contact?enquiry=demo">Book a demo <ArrowIcon/></Link><a className="text-link" href="#platform">Explore the platform <ArrowIcon direction="down"/></a></div><div className="hero-note"><span className="note-icon">✳</span><span>Made for the people<br/><b>who make hospitality happen.</b></span></div></div>
  <div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="product-window"><div className="window-bar"><span className="window-brand"><img src="/branding/pace-light.png" alt="Pace"/></span><div><b>Diary</b><span>Rewards</span><span>Settings</span></div><span className="avatar">JT</span></div><Diary/></div><div className="floating-reward"><span className="gift">✧</span><div><b>A little extra, on us.</b><span>Reward created · 100 points</span></div><span className="tick">✓</span></div><div className="visual-caption"><span>LESS ADMIN.</span><span>MORE HOSPITALITY.</span></div></div></section>
  <section className="venue-strip" aria-label="Who Pace is for"><span>GOOD COMPANY FOR</span><p>Restaurants</p><i>✳</i><p>Cafés</p><i>✳</i><p>Pubs & bars</p><i>✳</i><p>Independent venues</p></section>
  <section className="platform wrap" id="platform"><div className="section-heading"><div><p className="eyebrow">ONE CONNECTED BACK OFFICE</p><h2>Find your flow.<br/>Keep your <em>Pace.</em></h2></div><p>From the first booking to the next visit, give your team a shared view of what matters.</p></div><div className="feature-tabs" role="tablist" aria-label="Platform features">{features.map((f,i)=><button key={f.name} role="tab" id={`tab-${i}`} aria-selected={active===i} aria-controls="feature-panel" onClick={()=>setActive(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(active+(e.key==='ArrowRight'?1:2))%3;setActive(next);document.getElementById(`tab-${next}`)?.focus();}}} tabIndex={active===i?0:-1}><span>0{i+1}</span>{f.name}</button>)}</div>
  <div className="feature-panel" id="feature-panel" role="tabpanel" aria-labelledby={`tab-${active}`}><div className="feature-copy"><p className="eyebrow">{feature.eyebrow}</p><h3>{feature.title}</h3><p>{feature.description}</p><ul>{feature.points.map(p=><li key={p}><span>✓</span>{p}</li>)}</ul></div><div className="feature-demo">{active===0?<Diary compact/>:active===1?<div className="menu-demo"><span className="mini-label">THE SEASONAL EDIT</span><h3>Fresh from the kitchen.</h3>{[['Burrata & heritage tomatoes','£9.50','Vegetarian'],['Pan-roasted sea bass','£23.00','Available'],['Wild mushroom risotto','£17.50','Vegetarian']].map(([name,price,status])=><div key={name}><span><b>{name}</b><small>{status}</small></span><strong>{price}</strong></div>)}<p>Illustrative menu</p></div>:<div className="reward-demo"><span className="reward-star">✳</span><p>A LITTLE THANK YOU</p><h3>100<span>points</span></h3><code>QT8F4M7R2K9P6A</code><p>One code. One happy customer.</p><small>Illustrative reward · App scanning coming later</small></div>}</div></div>  <nav className="seo-links" aria-label="Explore Pace features">{seoFeatures.map(f=><Link key={f.slug} href={`/features/${f.slug}`}>{f.title} <ArrowIcon direction="right"/></Link>)}</nav></section>

  <section className="guest-preview wrap" aria-labelledby="guest-preview-title">
    <div className="section-heading"><div><p className="eyebrow">FOR YOUR TEAM. FOR YOUR GUESTS.</p><h2 id="guest-preview-title">A clearer service.<br/><em>A simpler visit.</em></h2></div><p>Your team plans the day in the booking diary. Guests choose a time, review their details and keep their next visit close in the companion app.</p></div>
    <div className="guest-preview-grid">
      {[['image2.png', 'Choose a time', 'A booking screen with experiences, party sizes and available times.'], ['image1.png', 'Check the details', 'A booking review screen with visit details and guest information.'], ['image3.png', 'Keep the visit close', 'The guest home screen with upcoming visits, menus and rewards.']].map(([file, title, description], i) => <figure key={file}><a href={`/app-screens/${file}`} target="_blank" rel="noreferrer" aria-label={`View full-size preview: ${title} (opens in a new tab)`}><img src={`/app-screens/${file}`} alt={description} loading="lazy"/></a><figcaption><span>0{i + 1}</span><h3>{title}</h3><p>{description}</p></figcaption></figure>)}
    </div>
    <div className="guest-preview-footer"><p>Guest app previews. Features and rollout scope are confirmed for your venue; reward scanning is planned.</p><Link className="text-link" href="/app">Explore the guest app <ArrowIcon/></Link></div>
  </section>



  <section className="how" id="how-it-works"><div className="wrap"><p className="eyebrow">A BETTER RHYTHM, EVERY DAY</p><h2>Less juggling.<br/>More <em>looking after people.</em></h2><div className="steps">{[['01','Make it yours.','Set up your tables, service hours and menu to match the way your venue runs.'],['02','Bring service together.','Give your team a clear picture of bookings, guests and what’s on the menu.'],['03','Make the next visit count.','Recognise your regulars and turn a thoughtful reward into a reason to return.']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="home-pricing wrap" aria-labelledby="home-pricing-title"><div><p className="eyebrow">A STARTING POINT FOR YOUR VENUE</p><h2 id="home-pricing-title">Your service.<br/><em>Your next step.</em></h2><p>Start with bookings and menus, or bring customer rewards into the same back office.</p><Link className="text-link" href="/pricing">Compare plans and pricing details <ArrowIcon/></Link></div><div className="home-plan"><span>Pace core</span><strong className="home-promo">50% off for the first 6 months</strong><h3>£29 <del>£59</del> <small>/ venue / month</small></h3><p>Booking diary, table assignments, service hours and menus.</p><Link href="/contact?enquiry=demo">Book a demo <ArrowIcon/></Link></div><div className="home-plan"><span>Pace growth</span><strong className="home-promo">50% off for the first 6 months</strong><h3>£49 <del>£99</del> <small>/ venue / month</small></h3><p>Everything in Core, plus customer points and reward codes.</p><Link href="/contact?enquiry=demo">Book a demo <ArrowIcon/></Link></div><p className="home-pricing-note">Introductory prices are 50% off for the first six months; standard prices then apply. Annual plans have separate introductory and renewal pricing. Prices exclude VAT. Setup, guest app scope and contract terms are confirmed in your quote.</p></section>
  <section className="faq wrap" id="questions"><div><p className="eyebrow">A FEW GOOD QUESTIONS</p><h2>Let’s clear<br/>the <em>table.</em></h2></div><div className="faq-list">{[['Who is Pace designed for?','Pace is designed for hospitality teams managing table bookings, menus and customer loyalty, from independent cafés to restaurants and pubs.'],['What can I manage in the back office?','The back office brings together a visual booking diary, table assignments, opening and kitchen hours, menu maintenance and customer reward points.'],['How do rewards work?','Create a single-use code worth 0–1,000 points, choose an expiry date and download its QR code. You can also add points to an existing customer with an audited reason. Customer app scanning is planned for a later update.'],['Can I set different kitchen hours each day?','Yes. Set kitchen closing and venue closing separately for every day. Bookings must start before the kitchen closes and finish before the venue closes.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="closing wrap" id="explore"><div><p className="eyebrow">SERVICE IN SYNC</p><h2>Good hospitality<br/>has a <em>rhythm.</em></h2><p>Give your team the space to find theirs.</p></div><Link className="button" href="/contact?enquiry=demo">Book a demo <ArrowIcon/></Link><img className="closing-art" src="/branding/P.png" alt="" aria-hidden="true"/></section>
  </main><SiteFooter/>
</>;}
