'use client';
import { useState } from 'react';
import Link from 'next/link';
import { features as seoFeatures } from '../lib/features';
import { SiteFooter } from './SiteChrome';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronDown } from '@fortawesome/free-solid-svg-icons';
const features = [
  { name: 'Bookings', eyebrow: 'A clearer view of service', title: 'Every table. Every booking. One place.', description: 'See what’s coming, assign the right tables and keep your team a step ahead. Set service hours that work for your kitchen.', points: ['A visual booking diary', 'Table capacities and assignments', 'Configurable kitchen closing times'] },
  { name: 'Menus', eyebrow: 'Keep everyone on the same page', title: 'Your menu, ready for service.', description: 'Keep dishes, prices and availability organised from one back office, with dietary information where your team needs it.', points: ['Organised menus and sections', 'Dish prices and availability', 'Dietary information'] },
  { name: 'Rewards', eyebrow: 'Give them a reason to return', title: 'A little thank you goes a long way.', description: 'Create points rewards with individual QR codes, choose their expiry and add customer points with a clear record of every credit.', points: ['Single-use reward codes', 'Flexible points and expiry dates', 'Customer balances and history'] },
];
function Logo({dark=false}:{dark?:boolean}) { return <span className="logo"><img src={`/branding/pace-${dark?'dark':'light'}.png`} width="1448" height="1086" alt="Pace — Service in Sync" /></span>; }
function Diary({compact=false}:{compact?:boolean}) { return <div className={`diary ${compact?'compact':''}`} aria-label="Illustrative booking diary">
  <div className="diary-top"><div><span className="mini-label">YOUR SERVICE, AT A GLANCE</span><h3>Friday’s looking good.</h3></div><span className="live"><i/> Service ready</span></div>
  <div className="diary-stats"><div><b>24</b><span>reservations</span></div><div><b>86</b><span>guests expected</span></div><div><b>12</b><span>tables in sync</span></div><span className="date-chip">FRI, 18 SEPT</span></div>
  <div className="timeline"><div className="time-row"><span>TABLE</span>{['17:00','18:00','19:00','20:00','21:00'].map(t=><span key={t}>{t}</span>)}</div>
    {[['01','2 seats','Olivia · 2 guests','early'],['02','4 seats','James · 4 guests','late'],['03','6 seats','Sophie · 6 guests','middle'],['04','2 seats','Amir · 2 guests','early'],['05','4 seats','Ella · 3 guests','late']].map(([id,seats,name,position],i)=><div className="table-row" key={id}><div className="table-label"><b>{id}</b><small>{seats}</small></div><div className="track"><div className={`reservation ${position} shade-${i%3}`}><b>{name}</b><small>Confirmed</small></div></div></div>)}
  </div><div className="diary-bottom"><span><i/> Everything in its place.</span><small>Illustrative product view</small></div>
</div>; }
export default function Home(){ const [active,setActive]=useState(0);const [menu,setMenu]=useState(false); const feature=features[active];return <>
  <a className="skip" href="#main">Skip to content</a>
  <header className="header"><Link href="/" scroll aria-label="Pace home"><Logo/></Link><button className={`menu-toggle${menu?' is-open':''}`} aria-expanded={menu} aria-controls="navigation" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}><span/><span/><span/></button><nav id="navigation" className={menu?'open':''} aria-label="Main navigation"><Link href="/capabilities" scroll onClick={()=>setMenu(false)}>Capabilities</Link><Link href="/platform" scroll onClick={()=>setMenu(false)}>The platform</Link><Link href="/app" scroll onClick={()=>setMenu(false)}>Guest app</Link><Link href="/pricing" scroll onClick={()=>setMenu(false)}>Pricing</Link><Link href="/developers" scroll onClick={()=>setMenu(false)}>Developers</Link><Link href="/how-it-works" scroll onClick={()=>setMenu(false)}>How it works</Link><Link href="/faqs" scroll onClick={()=>setMenu(false)}>FAQs</Link><div className="nav-dropdown"><button className="nav-dropdown-trigger" type="button">Explore <FontAwesomeIcon icon={faChevronDown} aria-hidden="true"/></button><div className="nav-dropdown-panel"><Link href="/about" onClick={()=>setMenu(false)}>About Pace</Link><Link href="/integrations" onClick={()=>setMenu(false)}>Integrations</Link><Link href="/use-cases" onClick={()=>setMenu(false)}>Use cases</Link><Link href="/resources" onClick={()=>setMenu(false)}>Resources</Link><Link href="/restaurants" onClick={()=>setMenu(false)}>For restaurants</Link><Link href="/cafes" onClick={()=>setMenu(false)}>For cafés</Link><Link href="/pubs-bars" onClick={()=>setMenu(false)}>For pubs & bars</Link><Link href="/customer-journey" onClick={()=>setMenu(false)}>Customer journey</Link><Link href="/for-venue-owners" onClick={()=>setMenu(false)}>For venue owners</Link><Link href="/implementation" onClick={()=>setMenu(false)}>Implementation</Link><Link href="/product-tour" onClick={()=>setMenu(false)}>Product tour</Link></div></div></nav><Link className="button button-small header-cta" href="/contact" scroll>Talk to Pace <span>↗</span></Link></header>
  <main id="main"><section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><span/> RESTAURANT & HOSPITALITY MANAGEMENT SOFTWARE</p><h1>Great service.<br/>Less friction.<br/><em>That’s Pace.</em></h1><p className="intro">Restaurant management software that brings your bookings, menus and customer rewards together. More time for your guests. A better rhythm for your team.</p><div className="hero-actions"><a className="button" href="#platform">Explore the platform <span>↗</span></a><a className="text-link" href="#how-it-works">See how it works <span>↓</span></a></div><div className="hero-note"><span className="note-icon">✳</span><span>Made for the people<br/><b>who make hospitality happen.</b></span></div></div>
  <div className="hero-visual"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="product-window"><div className="window-bar"><span className="window-brand"><img src="/branding/pace-light.png" alt="Pace"/></span><div><b>Diary</b><span>Rewards</span><span>Settings</span></div><span className="avatar">JT</span></div><Diary/></div><div className="floating-reward"><span className="gift">✧</span><div><b>A little extra, on us.</b><span>Reward created · 100 points</span></div><span className="tick">✓</span></div><div className="visual-caption"><span>LESS ADMIN.</span><span>MORE HOSPITALITY.</span></div></div></section>
  <section className="venue-strip" aria-label="Who Pace is for"><span>GOOD COMPANY FOR</span><p>Restaurants</p><i>✳</i><p>Cafés</p><i>✳</i><p>Pubs & bars</p><i>✳</i><p>Independent venues</p></section>
  <section className="platform wrap" id="platform"><div className="section-heading"><div><p className="eyebrow">ONE CONNECTED BACK OFFICE</p><h2>Find your flow.<br/>Keep your <em>Pace.</em></h2></div><p>From the first booking to the next visit, give your team a shared view of what matters.</p></div><div className="feature-tabs" role="tablist" aria-label="Platform features">{features.map((f,i)=><button key={f.name} role="tab" id={`tab-${i}`} aria-selected={active===i} aria-controls="feature-panel" onClick={()=>setActive(i)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const next=(active+(e.key==='ArrowRight'?1:2))%3;setActive(next);document.getElementById(`tab-${next}`)?.focus();}}} tabIndex={active===i?0:-1}><span>0{i+1}</span>{f.name}<span>↗</span></button>)}</div>
  <div className="feature-panel" id="feature-panel" role="tabpanel" aria-labelledby={`tab-${active}`}><div className="feature-copy"><p className="eyebrow">{feature.eyebrow}</p><h3>{feature.title}</h3><p>{feature.description}</p><ul>{feature.points.map(p=><li key={p}><span>✓</span>{p}</li>)}</ul></div><div className="feature-demo">{active===0?<Diary compact/>:active===1?<div className="menu-demo"><span className="mini-label">THE SEASONAL EDIT</span><h3>Fresh from the kitchen.</h3>{[['Burrata & heritage tomatoes','£9.50','Vegetarian'],['Pan-roasted sea bass','£23.00','Available'],['Wild mushroom risotto','£17.50','Vegetarian']].map(([name,price,status])=><div key={name}><span><b>{name}</b><small>{status}</small></span><strong>{price}</strong></div>)}<p>Illustrative menu</p></div>:<div className="reward-demo"><span className="reward-star">✳</span><p>A LITTLE THANK YOU</p><h3>100<span>points</span></h3><code>QT8F4M7R2K9P6A</code><p>One code. One happy customer.</p><small>Illustrative reward · App scanning coming later</small></div>}</div></div><nav className="seo-links" aria-label="Explore Pace features">{seoFeatures.map(f=><Link key={f.slug} href={`/features/${f.slug}`}>{f.title} →</Link>)}</nav></section>
  <section className="capabilities wrap" id="capabilities"><div className="section-heading"><div><p className="eyebrow">WHAT THE SYSTEM DOES</p><h2>One system for<br/><em>the working day.</em></h2></div><p>Pace gives hospitality teams the practical tools to plan service, maintain customer-facing information and build repeat visits from one connected back office.</p></div><div className="capability-grid"><article><span>01</span><h3>Plan every service</h3><p>Manage reservations in a visual diary, see guest numbers at a glance, configure table capacities and assign tables that fit each booking.</p></article><article><span>02</span><h3>Control the details</h3><p>Set venue and kitchen closing times by day, organise menus into sections, maintain dish prices and availability, and keep dietary information close to the catalogue.</p></article><article><span>03</span><h3>Build customer loyalty</h3><p>Create single-use QR rewards worth 0–1,000 points, choose expiry dates, credit existing customers and keep an auditable reason for every manual points change.</p></article><article><span>04</span><h3>Keep teams aligned</h3><p>Give staff one place to review bookings, menus and rewards. Changes stay visible in the back office so the team can act on the latest service information.</p></article></div><p className="capabilities-note">Customer app scanning and staff code entry are planned for a later update; manual customer points credits are available now.</p></section>
  <section className="companion-section wrap" aria-labelledby="companion-title"><div className="companion-copy"><p className="eyebrow">THE COMPANION GUEST APP</p><h2 id="companion-title">The operation behind the visit. <em>The experience guests remember.</em></h2><p className="companion-lead">Pace is not only a back-office tool. The companion app gives guests a simple way to book, browse menus, keep upcoming visits close and stay connected to your venue.</p><p>When the team updates the operation, the guest experience has a stronger foundation. When guests book and return, the team has the context to deliver a more considered service.</p><div className="companion-actions"><Link className="button" href="/app">Explore the guest app <span>↗</span></Link><Link className="text-link" href="/guest-app-back-office">See both sides of Pace <span>↗</span></Link></div><div className="companion-points"><span><b>Book</b><small>with confidence</small></span><span><b>Visit</b><small>with context</small></span><span><b>Return</b><small>with a reason</small></span></div></div><div className="companion-visual"><div className="phone-frame"><img src="/app-screens/image3.png" alt="Pace companion guest app showing upcoming visits, rewards and menu actions"/></div><div className="companion-card"><span className="mini-label">UPCOMING VISIT</span><strong>Friday · 7:30pm</strong><small>Booking details, menu and rewards in one familiar place.</small></div></div></section>
  <section className="launch-panel wrap"><div className="launch-intro"><p className="eyebrow">READY WHEN YOU ARE</p><h2>See how Pace could fit <em>your service.</em></h2><p>Start with a product demo, explore a focused pilot or talk to us about the integrations you want to build around your operation.</p></div><div className="launch-actions"><a className="button" href="/contact">Book a demo <span>↗</span></a><a className="launch-link" href="/contact">Discuss a pilot <span>↗</span></a><a className="launch-link" href="/developers">Explore the API plan <span>↗</span></a></div><div className="launch-trust"><span>Built for practical rollout</span><a href="/security">Read about security and data <span>↗</span></a></div></section>
  <section className="workflow wrap" aria-labelledby="workflow-title"><div className="workflow-intro"><p className="eyebrow">FROM SETUP TO SERVICE</p><h2 id="workflow-title">Everything your team needs, <em>without the extra tabs.</em></h2><p>Set the rules once, keep the information current and give every shift a reliable view of what is happening next.</p></div><div className="workflow-list"><article><span>01</span><div><h3>Configure your venue</h3><p>Add tables and capacities, set opening and kitchen hours, and shape the system around the way your venue actually runs.</p></div></article><article><span>02</span><div><h3>Run the day from one diary</h3><p>Review reservations, party sizes, notes and table assignments in a shared service view that is easy to scan before and during a shift.</p></div></article><article><span>03</span><div><h3>Keep guests coming back</h3><p>Recognise regulars with trackable rewards and maintain a clear record of the points your team has issued.</p></div></article></div></section>
  <section className="value-section"><div className="wrap"><p className="eyebrow">WHY PACE</p><h2>Software that respects the <em>pace of service.</em></h2><div className="value-grid"><article><span>Less admin</span><h3>See the shift before it starts.</h3><p>A clear operational view helps teams prepare for the shape of the service instead of piecing it together from separate tools.</p></article><article><span>More consistency</span><h3>Keep the details where people need them.</h3><p>Tables, hours, menu information and rewards live in one back office, so the latest version is easier for the team to find.</p></article><article><span>Better follow-through</span><h3>Turn thoughtful moments into repeat visits.</h3><p>Give customer rewards a clear value, expiry and history so recognition feels personal without becoming another manual process.</p></article></div></div></section>
  <section className="how" id="how-it-works"><div className="wrap"><p className="eyebrow">A BETTER RHYTHM, EVERY DAY</p><h2>Less juggling.<br/>More <em>looking after people.</em></h2><div className="steps">{[['01','Make it yours.','Set up your tables, service hours and menu to match the way your venue runs.'],['02','Bring service together.','Give your team a clear picture of bookings, guests and what’s on the menu.'],['03','Make the next visit count.','Recognise your regulars and turn a thoughtful reward into a reason to return.']].map(([n,title,copy])=><article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>
  <section className="faq wrap" id="questions"><div><p className="eyebrow">A FEW GOOD QUESTIONS</p><h2>Let’s clear<br/>the <em>table.</em></h2></div><div className="faq-list">{[['Who is Pace designed for?','Pace is designed for hospitality teams managing table bookings, menus and customer loyalty, from independent cafés to restaurants and pubs.'],['What can I manage in the back office?','The back office brings together a visual booking diary, table assignments, opening and kitchen hours, menu maintenance and customer reward points.'],['How do rewards work?','Create a single-use code worth 0–1,000 points, choose an expiry date and download its QR code. You can also add points to an existing customer with an audited reason. Customer app scanning is planned for a later update.'],['Can I set different kitchen hours each day?','Yes. Set kitchen closing and venue closing separately for every day. Bookings must start before the kitchen closes and finish before the venue closes.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="closing wrap" id="explore"><div><p className="eyebrow">SERVICE IN SYNC</p><h2>Good hospitality<br/>has a <em>rhythm.</em></h2><p>Give your team the space to find theirs.</p></div><a className="button" href="#platform">Find your Pace <span>↗</span></a><span className="closing-art" aria-hidden="true">P</span></section>
  </main><SiteFooter/>
</>;}
