'use client';

import Link from 'next/link';
import { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faChevronDown } from '@fortawesome/free-solid-svg-icons';
import { ArrowIcon, WhatsAppArrow, whatsappUrl } from './WhatsAppLink';

export function SiteHeader() {
  const [menu, setMenu] = useState(false);
  const closeMenu = () => setMenu(false);
  const explore = [['About Pace','/about'],['Platform overview','/platform-overview'],['Platform map','/platform-map'],['Integrations','/integrations'],['Use cases','/use-cases'],['Resources','/resources'],['Operations centre','/operations-centre'],['Workflow examples','/workflow-examples'],['Getting started','/getting-started'],['Restaurants','/restaurants'],['Cafes','/cafes'],['Pubs & bars','/pubs-bars'],['Customer journey','/customer-journey'],['For venue owners','/for-venue-owners'],['Implementation','/implementation'],['Support','/support'],['Product tour','/product-tour'],['Guest app + back office','/guest-app-back-office'],['Compare approaches','/comparison']];
  return <header className="header"><Link href="/" aria-label="Pace home"><span className="logo"><img src="/branding/pace-light.png" width="1448" height="1086" alt="Pace — Service in Sync"/></span></Link><button className={`menu-toggle${menu?' is-open':''}`} aria-expanded={menu} aria-controls="navigation" aria-label={menu?'Close menu':'Open menu'} onClick={()=>setMenu(!menu)}><span/><span/><span/></button><nav id="navigation" className={menu?'open':''} aria-label="Main navigation"><Link href="/capabilities" onClick={closeMenu}>Capabilities</Link><Link href="/platform" onClick={closeMenu}>The platform</Link><Link href="/app" onClick={closeMenu}>Guest app</Link><Link href="/pricing" onClick={closeMenu}>Pricing</Link><Link href="/developers" onClick={closeMenu}>Developers</Link><Link href="/how-it-works" onClick={closeMenu}>How it works</Link><Link href="/faqs" onClick={closeMenu}>FAQs</Link><div className="nav-dropdown"><button className="nav-dropdown-trigger" type="button">Explore <FontAwesomeIcon icon={faChevronDown} aria-hidden="true"/></button><div className="nav-dropdown-panel">{explore.map(([label,href])=><Link key={href} href={href} onClick={closeMenu}>{label}</Link>)}</div></div></nav><a className="button button-small header-cta" href={whatsappUrl} target="_blank" rel="noreferrer">Talk to Pace <WhatsAppArrow/></a></header>;
}

export function SiteFooter() {
  return <footer className="site-footer wrap"><div className="footer-brand"><Link href="/" aria-label="Pace home">Pace — Service in Sync</Link><p>Thoughtful software. Better service.</p></div><div className="footer-column"><p className="footer-heading">Platform</p><nav aria-label="Platform links"><Link href="/platform">The platform</Link><Link href="/platform-overview">Platform overview</Link><Link href="/platform-map">Platform map</Link><Link href="/app">Guest app</Link><a href="https://app.pacevenues.com/">Try the guest app</a><Link href="/guest-app-back-office">Guest app + back office</Link><Link href="/capabilities">Capabilities</Link></nav></div><div className="footer-column"><p className="footer-heading">Explore</p><nav aria-label="Explore links"><Link href="/operations-centre">Operations centre</Link><Link href="/workflow-examples">Workflow examples</Link><Link href="/use-cases">Use cases</Link><Link href="/resources">Resources</Link><Link href="/getting-started">Getting started</Link><Link href="/implementation">Implementation</Link><Link href="/launch-checklist">Launch checklist</Link><Link href="/product-tour">Product tour</Link></nav></div><div className="footer-column"><p className="footer-heading">Company</p><nav aria-label="Company links"><Link href="/pricing">Pricing</Link><Link href="/business-case">Business case</Link><Link href="/developers">Developers</Link><Link href="/security">Security and data</Link><Link href="/support">Support</Link><Link href="/production-readiness">Production readiness</Link><Link href="/comparison">Compare approaches</Link><Link href="/faqs">FAQs</Link><Link href="/contact?enquiry=demo">Book a demo</Link></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Pace</span><nav aria-label="Legal links"><Link href="/privacy">Privacy</Link><Link href="/cookies">Cookie policy</Link><Link href="/terms">Terms</Link></nav><Link href="/">Back to top <ArrowIcon direction="up"/></Link></div></footer>;
}
