import {relationalContentReady} from './content';
import {replacePreferences} from './preferences';
import Fastify, {type FastifyReply, type FastifyRequest} from 'fastify';
import swagger from '@fastify/swagger';
import swaggerUi from '@fastify/swagger-ui';
import {z} from 'zod';
import {config} from './config';
import {contentManifest, currentContent, currentDataset, publishContent, publishDataset} from './content';
import {sql} from './db';
import {createAccessToken, createRefreshToken, expiredRefreshCookie, hashPassword, hashRefreshToken, parseCookies, refreshCookie, verifyAccessToken, verifyPassword} from './auth';
import {sendContactEmail, sendPasswordResetEmail} from './email';

const app = Fastify({logger: true});
app.addHook('onError', async (_request, _reply, error) => { if (error.code === 'P1001') error.statusCode = 409; });
const anyObject = {type: 'object', additionalProperties: true} as const;
await app.register(swagger, {openapi: {info: {title: 'Pace API', version: '0.3.0', description: 'Pace hospitality platform API for venue content, bookings, orders, loyalty and payments.'}, components: {securitySchemes: {adminToken: {type: 'http', scheme: 'bearer'}, bearerAuth: {type: 'http', scheme: 'bearer', bearerFormat: 'JWT'}}}}});
await app.register(swaggerUi, {routePrefix: '/docs', uiConfig: {docExpansion: 'list', persistAuthorization: true}});
const corsOrigins = (config.CORS_ORIGIN ?? '').split(',').map(origin => origin.trim()).filter(Boolean);
app.addHook('onRequest', async (request, reply) => {const origin=request.headers.origin;if(origin&&corsOrigins.includes(origin))reply.header('Access-Control-Allow-Origin',origin).header('Access-Control-Allow-Credentials','true').header('Vary','Origin');reply.header('Access-Control-Allow-Headers','Authorization, Content-Type').header('Access-Control-Allow-Methods','GET, POST, PATCH, PUT, DELETE, OPTIONS');});
app.options('*', async (_request, reply) => reply.code(204).send());
const admin = async (request: FastifyRequest, reply: FastifyReply) => {if (request.headers.authorization !== `Bearer ${config.API_ADMIN_TOKEN}`) return reply.code(401).send({message: 'Unauthorised'});};
const me = async (request: FastifyRequest) => {const bearer=request.headers.authorization?.match(/^Bearer\s+(.+)$/i)?.[1];const claims=bearer&&verifyAccessToken(bearer);if(!claims){const error=new Error('Authentication required.');(error as Error & {statusCode?:number}).statusCode=401;throw error;}const [row]=await sql<{id:string}[]>`select id from members where id=${claims.sub}`;if(!row){const error=new Error('Member not found.');(error as Error & {statusCode?:number}).statusCode=401;throw error;}return row;};
const params = z.object({id:z.string().uuid()});
const ownBooking = async (id:string, memberId:string) => {const [row] = await sql<{id:string}[]>`select id from bookings where id = ${id} and member_id = ${memberId}`; if (!row) throw new Error('Booking not found.'); return row;};
const recalc = async (orderId:string) => sql`update orders set total_pence = coalesce((select sum(unit_price_pence * quantity) from order_lines where order_id = ${orderId}),0), updated_at = now() where id = ${orderId}`;
const getOrder = async (bookingId:string, memberId:string, create=false) => {await ownBooking(bookingId, memberId); if (create) await sql`insert into orders (booking_id) values (${bookingId}) on conflict (booking_id) do nothing`; const [row] = await sql<{id:string; status:string; total_pence:number; paid_at:Date|null}[]>`select id,status,total_pence,paid_at from orders where booking_id=${bookingId}`; if (!row) throw new Error('Order not found.'); return row;};
const live = [{bearerAuth: []}];
app.post('/contact', {schema: {tags: ['Marketing'], summary: 'Send a marketing enquiry', body: anyObject}}, async (request, reply) => {
    const body = z.object({
        name: z.string().trim().min(2).max(100),
        email: z.string().trim().email().max(254),
        venue: z.string().trim().min(2).max(120),
        venueCount: z.string().trim().max(40).optional(),
        enquiryType: z.string().trim().max(80).optional(),
        message: z.string().trim().min(10).max(4000)
    }).parse(request.body);
    try {
        await sendContactEmail({...body, email: body.email.toLowerCase()});
    } catch (error) {
        request.log.error(error, 'Contact email delivery failed');
        return reply.code(503).send({error: 'Contact email is temporarily unavailable. Please try again later.'});
    }
    return {ok: true};
});

app.get('/health',{schema:{tags:['System'],summary:'Health check'}},async()=>({ok:true}));
app.post('/auth/register',{schema:{tags:['Authentication'],summary:'Register a member account',body:anyObject}},async (request,reply)=>{const body=z.object({name:z.string().min(2).max(100),email:z.string().email(),password:z.string().min(8).max(128)}).parse(request.body);const email=body.email.trim().toLowerCase();const password=await hashPassword(body.password);const member=await sql.begin(async tx=>{const [existing]=await tx`select id from members where email=${email}`;if(existing){const error=new Error('An account already exists for this email address.');(error as Error & {statusCode?:number}).statusCode=409;throw error;}const [created]=await tx<{id:string;email:string;display_name:string}[]>`insert into members(email,display_name,member_since,tier) values(${email},${body.name.trim()},current_date,'Quicken Member') returning id,email,display_name`;await tx`insert into member_credentials(member_id,password_salt,password_hash) values(${created.id},${password.salt},${password.hash})`;await tx`insert into member_preferences(member_id) values(${created.id})`;await tx`insert into loyalty_accounts(member_id,points) values(${created.id},0)`;return created;});const refresh=createRefreshToken();await sql`insert into member_refresh_sessions(member_id,token_hash,expires_at) values(${member.id},${hashRefreshToken(refresh)},now()+interval '30 days')`;reply.header('Set-Cookie',refreshCookie(refresh));return {accessToken:createAccessToken({id:member.id,email:member.email,displayName:member.display_name}),member:{id:member.id,email:member.email,name:member.display_name}};});
app.post('/auth/login',{schema:{tags:['Authentication'],summary:'Sign in and issue access JWT',body:anyObject}},async (request,reply)=>{const body=z.object({email:z.string().email(),password:z.string().min(1)}).parse(request.body);const [member]=await sql<{id:string;email:string;display_name:string;password_salt:string;password_hash:string}[]>`select m.id,m.email,m.display_name,c.password_salt,c.password_hash from members m join member_credentials c on c.member_id=m.id where m.email=${body.email.trim().toLowerCase()}`;if(!member||!await verifyPassword(body.password,member.password_salt,member.password_hash)){const error=new Error('Email address or password is incorrect.');(error as Error & {statusCode?:number}).statusCode=401;throw error;}const refresh=createRefreshToken();await sql`insert into member_refresh_sessions(member_id,token_hash,expires_at) values(${member.id},${hashRefreshToken(refresh)},now()+interval '30 days')`;reply.header('Set-Cookie',refreshCookie(refresh));return {accessToken:createAccessToken({id:member.id,email:member.email,displayName:member.display_name}),member:{id:member.id,email:member.email,name:member.display_name}};});
app.post('/auth/refresh',{schema:{tags:['Authentication'],summary:'Rotate HttpOnly refresh session and issue an access JWT'}},async (request,reply)=>{const token=parseCookies(request.headers.cookie).qt_refresh;if(!token){const error=new Error('No active session.');(error as Error & {statusCode?:number}).statusCode=401;throw error;}const [session]=await sql<{id:string;member_id:string;email:string;display_name:string}[]>`select s.id,s.member_id,m.email,m.display_name from member_refresh_sessions s join members m on m.id=s.member_id where s.token_hash=${hashRefreshToken(token)} and s.revoked_at is null and s.expires_at>now()`;if(!session){reply.header('Set-Cookie',expiredRefreshCookie());const error=new Error('Session expired.');(error as Error & {statusCode?:number}).statusCode=401;throw error;}const refresh=createRefreshToken();await sql.begin(async tx=>{await tx`update member_refresh_sessions set revoked_at=now() where id=${session.id}`;await tx`insert into member_refresh_sessions(member_id,token_hash,expires_at) values(${session.member_id},${hashRefreshToken(refresh)},now()+interval '30 days')`;});reply.header('Set-Cookie',refreshCookie(refresh));return {accessToken:createAccessToken({id:session.member_id,email:session.email,displayName:session.display_name}),member:{id:session.member_id,email:session.email,name:session.display_name}};});
app.post('/auth/logout',{schema:{tags:['Authentication'],summary:'Revoke current refresh session'}},async (request,reply)=>{const token=parseCookies(request.headers.cookie).qt_refresh;if(token)await sql`update member_refresh_sessions set revoked_at=now() where token_hash=${hashRefreshToken(token)} and revoked_at is null`;reply.header('Set-Cookie',expiredRefreshCookie());return {ok:true};});
app.post('/auth/forgot-password',{schema:{tags:['Authentication'],summary:'Send a password reset link',body:anyObject}},async request=>{const {email}=z.object({email:z.string().email()}).parse(request.body);const [member]=await sql<{id:string;email:string;display_name:string}[]>`select id,email,display_name from members where email=${email.trim().toLowerCase()}`;if(member){const token=createRefreshToken();await sql.begin(async tx=>{await tx`update member_password_reset_tokens set used_at=now() where member_id=${member.id} and used_at is null`;await tx`insert into member_password_reset_tokens(member_id,token_hash,expires_at) values(${member.id},${hashRefreshToken(token)},now()+interval '30 minutes')`;});try{await sendPasswordResetEmail(member.email,member.display_name,token);}catch(error){app.log.error(error,'Password reset email could not be sent');}}return {ok:true};});
app.post('/auth/reset-password',{schema:{tags:['Authentication'],summary:'Set a new password with a one-time reset token',body:anyObject}},async request=>{const {token,password}=z.object({token:z.string().min(32),password:z.string().min(8).max(128)}).parse(request.body);const credentials=await hashPassword(password);const member=await sql.begin(async tx=>{const [reset]=await tx<{member_id:string}[]>`update member_password_reset_tokens set used_at=now() where token_hash=${hashRefreshToken(token)} and used_at is null and expires_at>now() returning member_id`;if(!reset){const error=new Error('This password reset link is invalid or has expired.');(error as Error & {statusCode?:number}).statusCode=400;throw error;}await tx`update member_credentials set password_salt=${credentials.salt},password_hash=${credentials.hash},updated_at=now() where member_id=${reset.member_id}`;await tx`update member_refresh_sessions set revoked_at=now() where member_id=${reset.member_id} and revoked_at is null`;return reset.member_id;});return {ok:true,memberId:member};});
// Cacheable datasets: menu, events, offers, rewards, opening rules, and profile options.
app.get('/content/manifest',{schema:{tags:['Content'],summary:'List versions of cacheable datasets'}},async()=>contentManifest());
app.get('/content/:key',{schema:{tags:['Content'],summary:'Download a dataset only if the cached version is stale'}},async request=>{const {key}=z.object({key:z.string().min(1)}).parse(request.params);const {version}=z.object({version:z.string().optional()}).parse(request.query);const data=await currentDataset(key);if(!data)return {statusCode:404,message:'Content dataset not found.'};return version===data.version?{key,version:data.version,updatedAt:data.updatedAt,changed:false}:{...data,changed:true};});
app.put('/admin/content/:key',{preHandler:admin,schema:{tags:['Content administration'],summary:'Publish one independently versioned dataset',security:[{adminToken:[]}],body:{type:'object',required:['data'],properties:{version:{type:'string'},data:anyObject}}}},async request=>{const {key}=z.object({key:z.string().min(1)}).parse(request.params);const body=z.object({version:z.string().optional(),data:z.record(z.string(),z.unknown())}).parse(request.body);return publishDataset(key,body.data,body.version);});
app.get('/content',{schema:{deprecated:true,tags:['Content'],summary:'Legacy aggregate content'}},async request=>{const {version}=z.object({version:z.string().optional()}).parse(request.query);const data=await currentContent();if(!data)return {statusCode:503,message:'Content not seeded.'};return version===data.version?{version:data.version,changed:false}:{...data,changed:true};});
app.get('/content-admin',{preHandler:admin,schema:{deprecated:true,tags:['Content administration'],security:[{adminToken:[]}]}},async()=>currentContent());
app.put('/content-admin',{preHandler:admin,schema:{deprecated:true,tags:['Content administration'],security:[{adminToken:[]}],body:anyObject}},async request=>{const body=z.object({version:z.string().optional(),data:z.record(z.string(),z.unknown())}).parse(request.body);return publishContent(body.data,body.version);});

app.get('/me/profile',{schema:{tags:['Member'],summary:'Live member profile',security:live}},async request=>{const member=await me(request);const [row]=await sql`select m.id,m.email,m.display_name as "displayName",m.member_since as "memberSince",m.tier,${sql.unsafe(relationalContentReady ? `coalesce((select json_agg(name order by position) from member_tastes where member_id=m.id),'[]') as tastes,coalesce((select json_agg(name order by position) from member_dietary_needs where member_id=m.id),'[]') as "dietaryNeeds"` : `p.tastes,p.dietary_needs as "dietaryNeeds"`)} from members m left join member_preferences p on p.member_id=m.id where m.id=${member.id}`;return row;});
app.patch('/me/profile',{schema:{tags:['Member'],summary:'Update live profile and preferences',security:live,body:anyObject}},async request=>{const member=await me(request);const body=z.object({displayName:z.string().min(1).optional(),email:z.string().email().optional(),tastes:z.array(z.string()).optional(),dietaryNeeds:z.array(z.string()).optional()}).parse(request.body);await sql.begin(async tx=>{if(body.displayName||body.email)await tx`update members set display_name=coalesce(${body.displayName??null},display_name),email=coalesce(${body.email??null},email),updated_at=now() where id=${member.id}`;if(body.tastes)await replacePreferences(tx,'member_tastes',member.id,body.tastes);if(body.dietaryNeeds)await replacePreferences(tx,'member_dietary_needs',member.id,body.dietaryNeeds);await tx`update member_preferences set updated_at=now() where member_id=${member.id}`;});return {ok:true};});
app.get('/me/loyalty',{schema:{tags:['Loyalty'],summary:'Current loyalty points',security:live}},async request=>{const member=await me(request);const [row]=await sql`select points,updated_at as "updatedAt" from loyalty_accounts where member_id=${member.id}`;return row??{points:0};});
app.get('/me/loyalty/ledger',{schema:{tags:['Loyalty'],summary:'Loyalty ledger',security:live}},async request=>{const member=await me(request);return sql`select id,points_delta as "pointsDelta",reason,reference_type as "referenceType",reference_id as "referenceId",created_at as "createdAt" from loyalty_ledger where member_id=${member.id} order by created_at desc`;});
app.get('/rewards',{schema:{tags:['Rewards'],summary:'Read cacheable reward catalogue'}},async()=>{const rewards=await currentDataset('rewards');if(!rewards)throw new Error('Rewards content not seeded.');return rewards;});
app.get('/me/rewards',{schema:{tags:['Rewards'],summary:'List member reward vouchers',security:live}},async request=>{const member=await me(request);return sql`select id,reward_code as "rewardCode",reward_title as "rewardTitle",points_spent as "pointsSpent",status,issued_at as "issuedAt",redeemed_at as "redeemedAt" from reward_redemptions where member_id=${member.id} order by issued_at desc`;});
app.post('/me/rewards/:code/redeem',{schema:{tags:['Rewards'],summary:'Exchange loyalty points for a reward voucher',security:live}},async request=>{const member=await me(request);const {code}=z.object({code:z.string().min(1)}).parse(request.params);const dataset=await currentDataset('rewards');const catalogue=z.object({rewards:z.array(z.object({code:z.string(),title:z.string(),meta:z.string()}))}).parse(dataset?.data);const reward=catalogue.rewards.find(item=>item.code===code);if(!reward)throw new Error('Reward not found.');const points=Number(reward.meta.match(/^([\d,]+) points/)?.[1].replace(/,/g,''));if(!Number.isInteger(points))throw new Error('Reward points are invalid.');return sql.begin(async tx=>{const [account]=await tx<{points:number}[]>`select points from loyalty_accounts where member_id=${member.id} for update`;if(!account||account.points<points)throw new Error('Not enough loyalty points.');const [voucher]=await tx<{id:string}[]>`insert into reward_redemptions(member_id,reward_code,reward_title,points_spent) values(${member.id},${reward.code},${reward.title},${points}) returning id`;await tx`update loyalty_accounts set points=points-${points},updated_at=now() where member_id=${member.id}`;await tx`insert into loyalty_ledger(member_id,points_delta,reason,reference_type,reference_id) values(${member.id},${-points},${'Reward redeemed: '+reward.title},'reward_redemption',${voucher.id})`;return {id:voucher.id,code:reward.code,title:reward.title,pointsSpent:points,status:'issued'};});});
app.post('/me/rewards/:id/mark-redeemed',{schema:{tags:['Rewards'],summary:'Mark a member voucher redeemed',security:live}},async request=>{const member=await me(request);const {id}=params.parse(request.params);const [voucher]=await sql`update reward_redemptions set status='redeemed',redeemed_at=now() where id=${id} and member_id=${member.id} and status='issued' returning id`;if(!voucher)throw new Error('Reward voucher not found or already redeemed.');return {ok:true};});

app.get('/bookings',{schema:{tags:['Bookings'],summary:'List current member bookings',security:live}},async request=>{const member=await me(request);return sql`select id,booking_date::text as date,booking_time::text as time,guest_count as "guestCount",experience,status,total_pence as "totalPence",contact_name as "contactName",${sql.unsafe(relationalContentReady ? `coalesce((select json_agg(name order by position) from booking_dietary_needs where booking_id=bookings.id),'[]')` : 'dietary_needs')} as "dietaryNeeds",updated_at as "updatedAt" from bookings where member_id=${member.id} order by booking_date,booking_time`;});
app.post('/bookings',{schema:{tags:['Bookings'],summary:'Create a booking',security:live,body:anyObject}},async request=>{const member=await me(request);const b=z.object({date:z.string().date(),time:z.string().regex(/^\d{2}:\d{2}$/),guestCount:z.number().int().positive().max(20),experience:z.string().default('Table'),totalPence:z.number().int().nonnegative().default(0),contactName:z.string().min(1),contactEmail:z.string().email().optional(),notes:z.string().optional(),dietaryNeeds:z.array(z.string()).default([]),guests:z.array(z.string()).default([])}).parse(request.body);const booking=await sql.begin(async tx=>{const [setting]=await tx<{minutes:number}[]>`select integer_value as minutes from booking_system_settings where setting_key='default_booking_duration_minutes'`;const [booking]=await tx<{id:string}[]>`insert into bookings(member_id,booking_date,booking_time,guest_count,experience,total_pence,contact_name,contact_email,notes,booking_duration_minutes) values(${member.id},${b.date},${b.time},${b.guestCount},${b.experience},${b.totalPence},${b.contactName},${b.contactEmail??null},${b.notes??null},${setting?.minutes??90}) returning id`;await replacePreferences(tx,'booking_dietary_needs',booking.id,b.dietaryNeeds);await Promise.all((b.guests.length?b.guests:[b.contactName]).map((name,index)=>tx`insert into booking_guests(booking_id,display_name,position) values(${booking.id},${name},${index+1})`));return booking;});return {id:booking.id,status:'confirmed'};});
app.get('/bookings/:id',{schema:{tags:['Bookings'],summary:'Booking details and guests',security:live}},async request=>{const member=await me(request);const {id}=params.parse(request.params);await ownBooking(id,member.id);const [booking]=await sql`select id,booking_date::text as date,booking_time::text as time,guest_count as "guestCount",experience,status,total_pence as "totalPence",contact_name as "contactName",contact_email as "contactEmail",notes,${sql.unsafe(relationalContentReady ? `coalesce((select json_agg(name order by position) from booking_dietary_needs where booking_id=bookings.id),'[]')` : 'dietary_needs')} as "dietaryNeeds",updated_at as "updatedAt" from bookings where id=${id}`;const guests=await sql`select id,display_name as "displayName",position from booking_guests where booking_id=${id} order by position`;return {...booking,guests};});
app.patch('/bookings/:id',{schema:{tags:['Bookings'],summary:'Update a booking',security:live,body:anyObject}},async request=>{const member=await me(request);const {id}=params.parse(request.params);await ownBooking(id,member.id);const b=z.object({time:z.string().regex(/^\d{2}:\d{2}$/).optional(),guestCount:z.number().int().positive().optional(),notes:z.string().nullable().optional(),dietaryNeeds:z.array(z.string()).optional()}).parse(request.body);await sql.begin(async tx=>{await tx`select id from bookings where id=${id} for update`;await tx`update bookings set booking_time=coalesce(${b.time??null},booking_time),guest_count=coalesce(${b.guestCount??null},guest_count),notes=coalesce(${b.notes??null},notes),updated_at=now() where id=${id}`;if(b.dietaryNeeds)await replacePreferences(tx,'booking_dietary_needs',id,b.dietaryNeeds);});return {ok:true};});
app.post('/bookings/:id/cancel',{schema:{tags:['Bookings'],summary:'Cancel booking and draft order',security:live}},async request=>{const member=await me(request);const {id}=params.parse(request.params);await ownBooking(id,member.id);await sql`update bookings set status='cancelled',updated_at=now() where id=${id}`;await sql`update orders set status='cancelled',updated_at=now() where booking_id=${id} and status='draft'`;return {ok:true};});
app.post('/bookings/:id/guests',{schema:{tags:['Bookings'],summary:'Add a named guest to a booking',security:live,body:anyObject}},async request=>{const member=await me(request);const {id}=params.parse(request.params);await ownBooking(id,member.id);const {displayName}=z.object({displayName:z.string().min(1).max(100)}).parse(request.body);const [guest]=await sql<{id:string;position:number}[]>`insert into booking_guests(booking_id,display_name,position) values(${id},${displayName},coalesce((select max(position)+1 from booking_guests where booking_id=${id}),1)) returning id,position`;return {...guest,displayName};});
app.patch('/bookings/:id/guests/:guestId',{schema:{tags:['Bookings'],summary:'Rename a booking guest',security:live,body:anyObject}},async request=>{const member=await me(request);const p=z.object({id:z.string().uuid(),guestId:z.string().uuid()}).parse(request.params);await ownBooking(p.id,member.id);const {displayName}=z.object({displayName:z.string().min(1).max(100)}).parse(request.body);const [guest]=await sql`update booking_guests set display_name=${displayName} where id=${p.guestId} and booking_id=${p.id} returning id`;if(!guest)throw new Error('Guest not found.');return {ok:true};});
app.delete('/bookings/:id/guests/:guestId',{schema:{tags:['Bookings'],summary:'Remove a booking guest',security:live}},async request=>{const member=await me(request);const p=z.object({id:z.string().uuid(),guestId:z.string().uuid()}).parse(request.params);await ownBooking(p.id,member.id);await sql`delete from booking_guests where id=${p.guestId} and booking_id=${p.id}`;return {ok:true};});

app.get('/bookings/:id/order',{schema:{tags:['Orders'],summary:'Read order ahead',security:live}},async request=>{const member=await me(request);const {id}=params.parse(request.params);const order=await getOrder(id,member.id);const lines=await sql`select id,item_name as "itemName",item_description as "itemDescription",unit_price_pence as "unitPricePence",quantity from order_lines where order_id=${order.id}`;const assignments=await sql`select a.id,a.order_line_id as "orderLineId",a.booking_guest_id as "bookingGuestId",a.serving_number as "servingNumber",a.is_shared as "isShared" from order_line_assignments a join order_lines l on l.id=a.order_line_id where l.order_id=${order.id}`;return {...order,lines,assignments};});
app.post('/bookings/:id/order',{schema:{tags:['Orders'],summary:'Create or resume draft order',security:live}},async request=>{const member=await me(request);const {id}=params.parse(request.params);return getOrder(id,member.id,true);});
app.post('/bookings/:id/order/lines',{schema:{tags:['Orders'],summary:'Add a draft order line',security:live,body:anyObject}},async request=>{const member=await me(request);const {id}=params.parse(request.params);const b=z.object({itemName:z.string().min(1),itemDescription:z.string().optional(),unitPricePence:z.number().int().nonnegative(),quantity:z.number().int().positive().max(20).default(1)}).parse(request.body);const order=await getOrder(id,member.id,true);if(order.status!=='draft')return {statusCode:409,message:'Only draft orders can be edited.'};const [line]=await sql<{id:string}[]>`insert into order_lines(order_id,item_name,item_description,unit_price_pence,quantity) values(${order.id},${b.itemName},${b.itemDescription??null},${b.unitPricePence},${b.quantity}) returning id`;await recalc(order.id);return line;});
app.patch('/orders/:id/lines/:lineId',{schema:{tags:['Orders'],summary:'Change draft line quantity (0 removes)',security:live,body:anyObject}},async request=>{const member=await me(request);const p=z.object({id:z.string().uuid(),lineId:z.string().uuid()}).parse(request.params);const {quantity}=z.object({quantity:z.number().int().min(0).max(20)}).parse(request.body);const [order]=await sql<{booking_id:string;status:string}[]>`select booking_id,status from orders where id=${p.id}`;if(!order)throw new Error('Order not found.');await ownBooking(order.booking_id,member.id);if(order.status!=='draft')return {statusCode:409,message:'Only draft orders can be edited.'};if(quantity)await sql`update order_lines set quantity=${quantity} where id=${p.lineId} and order_id=${p.id}`;else await sql`delete from order_lines where id=${p.lineId} and order_id=${p.id}`;await recalc(p.id);return {ok:true};});
app.put('/orders/:id/lines/:lineId/assignments/:serving',{schema:{tags:['Orders'],summary:'Assign a serving to guest or sharing',security:live,body:anyObject}},async request=>{const member=await me(request);const p=z.object({id:z.string().uuid(),lineId:z.string().uuid(),serving:z.coerce.number().int().positive()}).parse(request.params);const {bookingGuestId}=z.object({bookingGuestId:z.string().uuid().nullable().optional()}).parse(request.body);const [order]=await sql<{booking_id:string}[]>`select booking_id from orders where id=${p.id}`;if(!order)throw new Error('Order not found.');await ownBooking(order.booking_id,member.id);if(bookingGuestId){const [guest]=await sql`select id from booking_guests where id=${bookingGuestId} and booking_id=${order.booking_id}`;if(!guest)throw new Error('Guest does not belong to booking.');}await sql`insert into order_line_assignments(order_line_id,booking_guest_id,serving_number,is_shared) values(${p.lineId},${bookingGuestId??null},${p.serving},${!bookingGuestId}) on conflict(order_line_id,serving_number) do update set booking_guest_id=excluded.booking_guest_id,is_shared=excluded.is_shared`;return {ok:true};});
app.post('/orders/:id/checkout',{schema:{tags:['Orders'],summary:'Mark order paid after payment provider confirmation',security:live,body:anyObject}},async request=>{const member=await me(request);const {id}=params.parse(request.params);const {providerReference}=z.object({providerReference:z.string().min(4)}).parse(request.body);const [order]=await sql<{booking_id:string;status:string}[]>`select booking_id,status from orders where id=${id}`;if(!order)throw new Error('Order not found.');await ownBooking(order.booking_id,member.id);if(order.status!=='draft')return {statusCode:409,message:'Order is not a draft.'};await sql`update orders set status='paid',paid_at=now(),updated_at=now() where id=${id}`;return {ok:true,providerReference};});

app.get('/me/payment-methods',{schema:{tags:['Payments'],summary:'List payment tokens, never PAN',security:live}},async request=>{const member=await me(request);return sql`select id,provider,brand,last4,expires_at as "expiresAt" from payment_method_references where member_id=${member.id} order by created_at desc`;});
app.post('/me/payment-methods',{schema:{tags:['Payments'],summary:'Store provider token reference',security:live,body:anyObject}},async request=>{const member=await me(request);const b=z.object({provider:z.string().min(1),providerReference:z.string().min(1),brand:z.string().optional(),last4:z.string().regex(/^\d{4}$/).optional(),expiresAt:z.string().date().optional()}).parse(request.body);const [result]=await sql<{id:string}[]>`insert into payment_method_references(member_id,provider,provider_reference,brand,last4,expires_at) values(${member.id},${b.provider},${b.providerReference},${b.brand??null},${b.last4??null},${b.expiresAt??null}) returning id`;return result;});
app.delete('/me/payment-methods/:id',{schema:{tags:['Payments'],summary:'Delete payment provider reference',security:live}},async request=>{const member=await me(request);const {id}=params.parse(request.params);await sql`delete from payment_method_references where id=${id} and member_id=${member.id}`;return {ok:true};});

app.listen({port:config.PORT,host:'0.0.0.0'});
