import type { Metadata } from 'next';
import Link from 'next/link';
import { SiteFooter, SiteHeader } from '../SiteChrome';
import { ArrowIcon } from '../WhatsAppLink';
import { metadata } from '../../lib/seo';

export const generateMetadata = (): Metadata => metadata('The Pace Platform | Pace', 'Explore bookings, menus, customer lists, rewards and staff permissions in the connected Pace back office.', '/platform');

export default function PlatformPage() {
  return <><SiteHeader/><main className="subpage wrap"><p className="eyebrow">ONE CONNECTED BACK OFFICE</p><h1>Everything in its place. <em>Service in sync.</em></h1><p className="subpage-intro">Pace brings bookings, menus, customer records, rewards and staff access into one working view, with the guest app connected to the same venue information.</p><div className="platform-cards"><article><span>01</span><h2>Bookings & tables</h2><p>See reservations, guest counts and table assignments together in a visual diary. Configure capacities and keep the floor plan clear for every shift.</p><Link href="/features/restaurant-booking-software">Explore bookings <ArrowIcon direction="right"/></Link></article><article><span>02</span><h2>Menus & availability</h2><p>Organise dishes and sections, build selectable options with price differences, manage availability, and maintain dietary and allergen symbols for the guest menu.</p><Link href="/features/restaurant-menu-management">Explore menus <ArrowIcon direction="right"/></Link></article><article><span>03</span><h2>Rewards & loyalty</h2><p>Create individual points rewards with QR codes and expiry dates, then add customer credits with a reason and a complete ledger history.</p><Link href="/features/restaurant-loyalty-rewards">Explore rewards <ArrowIcon direction="right"/></Link></article><article><span>04</span><h2>Customer list</h2><p>Search registered app customers by name or email and see their loyalty balance, booking count and most recent booking at a glance.</p></article><article><span>05</span><h2>Users & permissions</h2><p>Create and manage staff accounts. Give booking access as read-only or read-write, and choose access to customers, rewards and each configuration area separately.</p></article><article><span>06</span><h2>Venue configuration</h2><p>Set table capacities, booking duration, opening and kitchen hours, menu symbols and reward availability from the back office.</p></article></div><div className="subpage-callout"><h2>Built around the way hospitality works.</h2><p>Start with the tools your team needs today, with a clear foundation for the customer experiences you want to build next.</p><Link className="button" href="/contact?enquiry=demo">Book a guided demo <span><ArrowIcon/></span></Link></div></main><SiteFooter/></>;
}
