import styles from './styles.module.css';
import {Icon} from '../../Icon';

type MenuSection = { title: string; items: ReadonlyArray<readonly [string, string, string]> };
type MenuCategory = { label: string; service: string; sections: MenuSection[] };
type CourseOffer = {heading: string; description: string; options: {label: string; courses: number; pricePence: number}[]; courses: {section: string; minSelections: number; maxSelections: number}[]};
type ItemOptionSet = {groups: {label: string; minSelections: number; maxSelections: number; options: string[]}[]};
type Props = {categories: MenuCategory[]; selectedCategory: string; onCategoryChange: (category: string) => void; search: string; onSearchChange: (value: string) => void; sections: MenuSection[]; dietaryTags: Record<string, string[]>; dietaryTagNames: Record<string, string>; outOfStockItems: Set<string>; courseOffer?: CourseOffer; onBuildCourseMenu: () => void; itemOptions: Record<string, ItemOptionSet>; onPromptItemOptions: (item: string) => void; orderAheadBooking: {guests: string; time: string} | null; serviceLabel?: string; onAdd: (name: string) => void; onPromptWings: () => void; onPromptWingsWednesday: () => void; onPromptPie: () => void; onBook: () => void};

export function MenuScreen({categories, selectedCategory, onCategoryChange, search, onSearchChange, sections, dietaryTags, dietaryTagNames, outOfStockItems, courseOffer, onBuildCourseMenu, itemOptions, onPromptItemOptions, orderAheadBooking, serviceLabel, onAdd, onPromptWings, onPromptWingsWednesday, onPromptPie, onBook}: Props) {
  const addItem = (name: string) => itemOptions[name] ? onPromptItemOptions(name) : name === 'Chicken Wings or Cauli Wings' ? onPromptWings() : name === 'Wings Wednesday' ? onPromptWingsWednesday() : name === 'Pie of the Day' ? onPromptPie() : onAdd(name);
  return <div className={styles.root}><p className="eyebrow">The Quicken Tree menu</p><h1>Good food,<br/>all day long.</h1>{orderAheadBooking && <p className="preOrderBanner"><Icon name="fa-utensils"/> Ordering ahead for {orderAheadBooking.guests} at {orderAheadBooking.time}{serviceLabel ? ` · ${serviceLabel}` : ''}</p>}<label className="menuSearch"><Icon name="fa-magnifying-glass"/><input value={search} onChange={event => onSearchChange(event.target.value)} placeholder="Search the menu"/></label><div className="menuTabs">{categories.map(category => <button key={category.label} className={selectedCategory === category.label ? 'selected' : ''} onClick={() => onCategoryChange(category.label)}>{category.label}</button>)}</div><p className="menuService">{categories.find(category => category.label === selectedCategory)?.service}</p>{courseOffer && <section className={styles.courseOffer} aria-label={courseOffer.heading}><div><p className="eyebrow">Set menu</p><h2>{courseOffer.heading}</h2><p>{courseOffer.description}</p></div><div className={styles.coursePrices}>{courseOffer.options.map(option => <span key={option.label}><b>£{(option.pricePence / 100).toFixed(0)}</b><small>{option.label}</small></span>)}</div>{orderAheadBooking && <button type="button" className={styles.buildCourse} onClick={onBuildCourseMenu}>Build your meal <Icon name="fa-arrow-right"/></button>}</section>}<p className="dietaryLegend">{(['V','VG','GF','VGO'] as const).map(tag => <span key={tag} title={dietaryTagNames[tag]}><em>{dietaryTagNames[tag]}</em></span>)}</p><div className="menuList">{sections.length ? sections.map(section => <section className="menuSection" key={section.title}><h2>{section.title}</h2>{section.items.map(([name,description,price]) => {const outOfStock = outOfStockItems.has(name); return <article className={`menuItem${outOfStock ? ` ${styles.outOfStock}` : ''}`} key={name}><div><b>{name}</b>{dietaryTags[name] && <span className="dietaryTags">{dietaryTags[name].map(tag => <mark key={tag} title={dietaryTagNames[tag]}>{tag}</mark>)}</span>}<p>{description}</p></div><aside>{price && <strong>{price}</strong>}{outOfStock ? <em className={styles.unavailable}>Out of stock</em> : orderAheadBooking && !courseOffer && <button className="addToOrder" onClick={() => addItem(name)} aria-label={`Add ${name} to order`}>Add</button>}</aside></article>;})}</section>) : <p className="noMenuResults">No menu items match “{search}”.</p>}</div>{orderAheadBooking ? null : <button className="cta" onClick={onBook}>Book a table</button>}</div>;
}
